Netgen\LiveVotingBundle\Entity\User:
    type: entity
    repositoryClass: Netgen\LiveVotingBundle\Entity\UserRepository
    table: user
    id:
        id:
            type: string
            length: 128
    fields:
        username:
            type: string
            length: 128
            nullable: true
        email:
            type: string
            length: 128
            nullable: true
        password:
            type: string
            length: 128
            nullable: true
        enabled:
            type: boolean
            default: true
            nullable: true
        gender:
            type: string
            length: '10'
            nullable: true
        country:
            type: string
            length: '128'
            nullable: true
        city:
            type: string
            length: '128'
            nullable: true
        tshirt:
            type: string
            length: '128'
            nullable: true
        foodPreference:
            type: string
            length: '128'
            nullable: true

    oneToMany:
        registrations:
            targetEntity: Netgen\LiveVotingBundle\Entity\Registration
            mappedBy: user
        presentations:
            targetEntity: Netgen\LiveVotingBundle\Entity\Presentation
            mappedBy: user
        presentationComments:
            targetEntity: Netgen\LiveVotingBundle\Entity\PresentationComment
            mappedBy: user
        presentationImages:
            targetEntity: Netgen\LiveVotingBundle\Entity\PresentationImage
            mappedBy: user
        eventAssociations:
            targetEntity: Netgen\LiveVotingBundle\Entity\UserEventAssociation
            mappedBy: user
        votes:
            targetEntity: Netgen\LiveVotingBundle\Entity\Vote
            mappedBy: user
